<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-08 at 11:53:48.
 */
class MyMathTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MyMath
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MyMath;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert (1,3) == 4.
     *
     * @covers MyMath::add
     */
    public function testAdd()
    {
        $this->assertEquals(
          4,
          $this->object->add(1,3)
        );
    }

    /**
     * Generated from @assert (2,2) == 4.
     *
     * @covers MyMath::add
     */
    public function testAdd2()
    {
        $this->assertEquals(
          4,
          $this->object->add(2,2)
        );
    }

    /**
     * Generated from @assert (2,3) == 4.
     *
     * @covers MyMath::add
     */
    public function testAdd3()
    {
        $this->assertEquals(
          5,
          $this->object->add(2,3)
        );
    }

    /**
     * @dataProvider provider
     */
    public function ttAddd($a,$b,$c) {
        $this->assertEquals($c,$a+$b);
    }

    public function provider() {
        return array(
            array(1,2,3),
            array(2,2,5)
        );
    }
}
